version: '3.8'

services:
  app:
    build:
      context: ./app
    env_file: .env
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
    depends_on:
      - app

  db:
    build:
      context: ./db
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge