version: '3.8'

services:

  db:
    build:
      context: ./db
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      - camagru-network

  camagru:
    build:
      context: ./camagru
    env_file: .env
    volumes:
      - ./camagru:/var/www/html
    networks:
      - camagru-network
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    ports:
      #- "8080:80"
      #- "8081:443"
      - "80:80"
      - "443:443"
    volumes:
      - ./camagru:/var/www/html
    networks:
      - camagru-network
    depends_on:
      - camagru

networks:
  camagru-network:
    driver: bridge