# ----------- NETWORKS -----------

networks:
  nginx_app:
    driver: bridge
  app_database:
    driver: bridge

# ----------- SERVICES -----------

services:

  nginx:  # Ajout du service NGINX
    container_name: nginx
    depends_on:
      - app
    env_file: .env
    build: ./nginx
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - nginx_app
    ports:
      - "80:80"    # Redirection HTTP
      - "443:443"  # Port HTTPS

  app:
    container_name: app
    env_file: .env
    volumes:
      - ./app:/app
    networks:
      - nginx_app
      - app_database
    depends_on:
      - database
    build: ./app
    restart: on-failure

  database:
    container_name: database
    env_file: .env
    networks:
      - app_database
    build: ./database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

# ----------- VOLUMES -----------

volumes:
  postgres-data: