version: '3'

# ----------- NETWORKS -----------

networks:
  frontend_backend:
    driver: bridge
  backend_database:
    driver: bridge

# ----------- SERVICES -----------

services:

  nginx:  # Ajout du service NGINX
    container_name: nginx
    depends_on:
      - frontend
    env_file: .env
    build: ./nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - frontend_backend
    ports:
      - "80:80"    # Redirection HTTP
      - "443:443"  # Port HTTPS

  frontend:
    container_name: frontend
    env_file: .env
    volumes:
      - ./frontend:/app
    networks:
      - frontend_backend
    depends_on:
      - backend
    build: ./frontend
    restart: on-failure

  backend:
    container_name: backend
    env_file: .env
    volumes:
      - ./backend:/app
    networks:
      - frontend_backend
      - backend_database
    build: ./backend
    depends_on:
      - database
    restart: on-failure
    ports:
      - "3000:3000"

  database:
    container_name: database
    env_file: .env
    networks:
      - backend_database
    build: ./database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

# ----------- VOLUMES -----------

volumes:
  postgres-data: